name: Build_on_platforms
on:
  push:
    branches: [ master, testing-ffi]
    paths:
      - '**'
      - '!README.md'
  pull_request:
    branches: [ master ]
    paths:
      - '**'
      - '!README.md'
defaults:
  run:
    working-directory: example

jobs:
  android_windows:
    name: Android_windows
    runs-on: windows-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build apk --split-per-abi 
  android_macos:
    name: Android_macos
    runs-on: macos-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build apk --split-per-abi 
  
  ios:
    name: iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build ios --no-codesign


